# Generated by Django 2.1.5 on 2019-01-31 14:27

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[rest_framework.compat.MinValueValidator(0)])),
            ],
        ),
    ]
