# Generated by Django 2.1.5 on 2019-01-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestor',
            name='msd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
