# Generated by Django 2.1.5 on 2019-02-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestor', '0002_ingestor_msd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenfordRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField()),
                ('separator', models.CharField(choices=[(',', 'comma'), ('\t', 'tab'), ('|', 'pipe')], max_length=12)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
