# Generated by Django 2.1.5 on 2019-02-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestor', '0003_benfordrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benfordrequest',
            name='separator',
            field=models.CharField(choices=[('comma', ','), ('tab', '\t'), ('pipe', '|')], max_length=12),
        ),
    ]
